### ISSUE TITLE
ListValue should be nullable

### ISSUE THREAD

**Issue by kwkbtr** [googleapis/proto-plus-python#106]
I am working on migration from Python code generated by protoc with `--python_out` to proto-plus, and found out that [`ListValue` is not nullable](https://proto-plus-python.readthedocs.io/en/latest/marshal.html#well-known-types) in proto-plus.
With the original code generated by protoc, `ListValue` is nullable (since it is a message) and our code assumes that.
In order to migrate to proto-plus we will need some extra work to check if our code works as intended with non-nullable `ListValue`.
I think this difference is incompatible with the original protoc-generated code.
Should not `ListValue` be nullable?

**Comment by hkdevandla** [comment]
@software-dov , just checking, what are the next steps for this in terms of fixing it?

**Comment by software-dov** [comment]
Implemented by #129
