### ISSUE TITLE
Accept both lowerCamelCase and snake_case for JSON proto representations

### ISSUE THREAD

**Issue by busunkim96** [googleapis/proto-plus-python#109]
JSON conversion methods should accept/produce both lowerCamelCase and snake_case.

The official [proto3 JSON spec](https://developers.google.com/protocol-buffers/docs/proto3#json) states that both are permissible. Both flavors exist in the [wild](https://cloud.google.com/document-ai/docs/reference/rest/v1beta2/Document).

[Protobuf](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html) names this option `preserving_proto_field_name`.

**Comment by software-dov** [comment]
Depends on #130

**Comment by software-dov** [comment]
From @busunkim96 :
> I think in practice most Cloud APIs use the camelCase representation so from_json and to_json are fine as is.

Deprioritizing to bump the SLO.
