### ISSUE TITLE
LICENSE file not included in source distribution on PyPI

### ISSUE THREAD

**Issue by tswast** [googleapis/proto-plus-python#141]
It's a best practice to include a LICENSE file in the source distribution. This way licenses can be audited by automated tooling.

Also, this is recommended to pass the linter on conda-forge.

**Comment by busunkim96** [comment]
@software-dov Unless you have any objections I'll open a PR to add a `MANIFEST.in`. It will also take care of #143. 

https://packaging.python.org/guides/using-manifest-in/

**Comment by busunkim96** [comment]
Closed by #146
