### ISSUE TITLE
Provide `ignore_unknown_fields=True` option in `from_json` and `from_dict`

### ISSUE THREAD

**Issue by tswast** [googleapis/proto-plus-python#153]
This blocking PR https://github.com/googleapis/python-bigquery/pull/332 (and as a result the `type` to `type_` change https://github.com/googleapis/python-bigquery/pull/316 and https://github.com/googleapis/python-bigquery/pull/328 with the new protobuf changes from the last year of updates from the BQML API -- though I might hack that one to ignore the `type` to `type_` change)

I'd quite like to actually use proto-plus in `google-cloud-bigquery` ( https://github.com/googleapis/python-bigquery/pull/332 ) rather than the current `_pb` workaround, but I can't without this change.

BigQuery very often launches new model types and model stats properties and updates the protos only after customers have used it in their projects. We need to be able to ignore unknown fields (and ideally unknown enums too, but that doesn't appear to be supported yet in the Python protobuf package https://github.com/protocolbuffers/protobuf/issues/7392)

**Comment by software-dov** [comment]
N.B.: It turns out ignoring unknown enums is already possible *iff* the unknown enum variant is passed as an integer.

**Comment by tswast** [comment]
That's good, but unfortunately the API send enums as strings.

**Comment by tswast** [comment]
I wouldn't make that a blocker, though since it's an issue in the underlying proto too
