### ISSUE TITLE
Recommended way to get ByteSize()

### ISSUE THREAD

**Issue by aabmass** [googleapis/proto-plus-python#163]
For regular `google.protobuf` objects, there is a [`ByteSize()`](https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.ByteSize) method. What is the best way to get a proto-plus instance's byte size? How about this approach:

```py
def get_byte_size(message):
    message_pb = message.__class__.pb(message)
    return message_pb.ByteSize()
```

It would be nice if proto plus messages included this method directly to maintain compatibility with APIs expecting regular `google.protobuf` messages.

----
For some additional context, this is coming up in the OpenCensus gRPC instrumentation, which annotates spans with size of messages: https://github.com/census-instrumentation/opencensus-python/issues/969. Newer versions of Google client libraries use proto-plus so [this code](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-grpc/opencensus/ext/grpc/utils.py#L18) hits an attribute error.

**Comment by aabmass** [comment]
I also noticed there is a "private" `message._pb` property. Is this safe to use?

**Comment by software-dov** [comment]
There isn't currently a direct method for determining byte size on proto-plus message instances. The escape hatch you found is safe and correct.
The `message._pb` property also has a class-method accessor:
```python
my_msg = MyMessage(arg1=arg1, arg2=arg2,...)
msg_size = MyMessage.pb(my_msg).ByteSize()
```

The accessor technically belongs to the `proto.MessageMeta` metaclass, which is why it can't be invoked directly by the instance. This is a pattern that emerged to prevent polluting the namespace of message fields.

**Comment by software-dov** [comment]
The two mechanisms you've found are just slightly different ways of doing the same thing.
The following also work and are fundamentally equivalent:
```python
import proto

my_msg = MyMessage()
pb1 = MyMessage.pb(my_msg)
pb2 = proto.Message.pb(my_msg)
pb3 = type(my_msg).pb(my_msg)
pb4 = my_msg.__class__.pb(my_msg)
pb5 = my_msg._pb

assert pb1 is pb2 is pb3 is pb4 is pb5
```
Of the above, the documentation predominantly uses variation 1. It's clean and straightforward and pays lip service to private fields.

The intention with proto-plus was to create a surface where common message manipulations were easy and pythonic. Completely recreating the protobuf surface and API is an explicit non-goal. There are a few other situations where we add a pass-through mechanism to support common use cases, though, such as JSON serialization and deserialization.

This is a small and well contained feature, so feel free to open a feature request to support it in the proto-plus surface, especially if you think it would help a large number of people or large projects.

**Comment by aabmass** [comment]
Thanks for the thorough response!

> This is a small and well contained mechansim, so feel free to open a feature request to support it in the proto-plus surface, especially if you think it would help a large number of people or large projects.

I'm really not really sure how useful this is to other projects. The code where I am seeing this is a gRPC interceptor that may receive classic protobuf or proto-plus instances depending on what is passed to the stub, so having API compatibility would be nice. There are plenty of workaround options though as you pointed out :)
