### ISSUE TITLE
add `preserving_proto_field_name` option to `to_dict` methods

### ISSUE THREAD

**Issue by tswast** [googleapis/proto-plus-python#166]
[MessageToDict](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html#google.protobuf.json_format.MessageToDict) provides a `preserving_proto_field_name` option to either preserve proto (snake_case) names or convert to `lowerCamelCase`.

This is blocking `google-cloud-bigquery` migration to `proto-plus` classes https://github.com/googleapis/python-bigquery/issues/319 as the existing client is relying on the default protobuf behavior (converts to `lowerCamelCase`)

**Comment by software-dov** [comment]
To clarify: is the client doing proto->dict conversion, or is it something the users may do and want to retain compatibility? Are there specific code paths or other features that are breaking, or is it more of a testing-headache fix?

**Comment by tswast** [comment]
More the latter "testing-headache fix". It was too much for our vendor to handle because there were more places than I realized that assume `lowerCamelCase`.

**Comment by tswast** [comment]
We do expose the JSON representation via a `to_api_repr` method (which was requested by some customers for archiving purposes). I suppose the switch to snake case could be considered a breaking change there.

**Comment by software-dov** [comment]
I think this may be blocked by a protobuf bug that does not respect JSON field name specification: https://github.com/protocolbuffers/protobuf/pull/7910
I'm not sure about that though.

**Comment by mik-laj** [comment]
This would also be a great help for Apache Airflow (Cloud Composer) as we could avoid breaking changes that affect large numbers of users.
Our use case is described in our documentation:
https://github.com/apache/airflow/blob/master/airflow/providers/google/ADDITIONAL_INFO.md
Our plans to migrate to new libraries are described in the tickets, but they are not very positive for users:
https://github.com/apache/airflow/issues/13230
https://github.com/apache/airflow/issues/12116
