### ISSUE TITLE
`=` should have transitive assignment for nested fields, not copying behavior

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/proto-plus-python#190]
The `=` operator is recommended to use in place of `CopyFrom` for nested message fields, so for example:

```py
# with proto-plus
message.nested = copy

# with raw protobuf messages
message.nested.CopyFrom(copy)
```

Syntactically this is nice, however it introduces unexpected behavior because the `=` operation in the first statement implicitly makes a copy of the second message.

With other Python objects, and in other programming languages, that `=` operator would make a transitive assignment so that `message.nested` and `copy` point to the same object in memory. So for example when using a `dict`:

```py
message = {}
copy = {"foo": "bar"}
message["copy"] = copy
message["copy"]["another"] = 1
print(copy)
>>> {"foo": "bar", "another": 1}
```

It might be better for the `=` operator to behave as it would for a `dict` or other objects, and to either expose a new interface specifically for copying objects, or to rely on conventional Python patterns like using the [`copy`](https://docs.python.org/3/library/copy.html) module.

**Comment by BenRKarl** [comment]
@software-dov we discussed this internally; given that reverting the existing behavior is probably too large of a breaking change to make, would it be possible to expose a `copy_from` method that delegates to the native `CopyFrom` method? We _can_ access it directly via `_pb.CopyFrom` but would prefer to avoid going through the private attribute.

**Comment by hkdevandla** [comment]
@software-dov , can you please take a look and give a rough idea about how much work is involved to implement the changes? We can discuss this tomorrow during our Ads sync. 

cc @miraleung.
