### ISSUE TITLE
Provide backwards compatibility for messages with timepoint or duration fields

### ISSUE THREAD

**Issue by software-dov** [googleapis/proto-plus-python#22]
Python `datetime` and `duration` only provide microsecond precision, while the protobuf `Timestamp` and `Duration` have nanosecond precision. This may lead to a loss of precision and invalid semantics.

One possibility would be to subclass `datetime` and `duration`.

**Comment by busunkim96** [comment]
CC @crwilcox @tseaver who had thoughts on how to manage datetimes.

**Comment by tseaver** [comment]
@software-dov We already have a subclass, `google.api_core.datetime_helpers.DatetimeWithNanoseconds`, designed specifically for this case. 

Python doesn't have `duration`:  it has `timedelta`:  we would need to subclass it as well.

**Comment by busunkim96** [comment]
Links to generated doc and class:
* https://googleapis.dev/python/google-api-core/1.14.3/helpers.html?highlight=datetime#module-google.api_core.datetime_helpers
* https://github.com/googleapis/google-cloud-python/blob/master/api_core/google/api_core/datetime_helpers.py

**Comment by software-dov** [comment]
My bad on mixing the names. Okay, it looks like the obvious solutions are A) add a dependency on api_core for the subclass, or B) duplicate the subclass. Thoughts?

**Comment by tseaver** [comment]
> A) add a dependency on api_core for the subclass

Icky in theory, assuming `protoc-plus-python` is aimed at broader usage than generating code for `google-cloud-*` libraries. I guess ideally the subclass(es) would live in `google.protobuf`, or else in some more tightly-scoped package that `api_core` and this package would both depend on.

> B) duplicate the subclass

Actually icky. We would need to duplicate the parsing helpers, too (at least `from_microseconds` and the epoch constant it uses).

**Comment by software-dov** [comment]
I think moving the subclass to `google.protobuf` would be the ideal. We should engage with those folks and see how vehemently opposed they are.

**Comment by lukesneeringer** [comment]
> My bad on mixing the names. Okay, it looks like the obvious solutions are A) add a dependency on api_core for the subclass, or B) duplicate the subclass. Thoughts?

C) Move the subclass here and have `google.api_core` import it at its old location.

**Comment by arithmetic1728** [comment]
Downgrade to p2 because it is way out of SLO for resolution, please raise it if needed.
