### ISSUE TITLE
proto-plus introduces substantial overhead to interactions with pb.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/proto-plus-python#222]
Profiled/Verified: https://github.com/googleapis/python-pubsub/pull/158

Suspected: https://github.com/googleapis/python-datastore/issues/145

It seems that the use of proto-plus is introducing somewhere between 40-150% overhead to client libraries when using proto plus.

**Comment by tseaver** [comment]
Today I [measured an order of magnitude](https://github.com/googleapis/python-datastore/issues/150#issuecomment-819688089) slowdown for datastore (unmarshaling query results to entities).

**Comment by craiglabenz** [comment]
Closing this, as the state of proto-plus performance optimizations is known to center around changing lines of code like this:

```py
my_proto_plus_object.some_attribute
```

into this:

```py
my_proto_plus_object._pb.some_attribute
```

to reclaim >= 90% of the lost performance.
