### ISSUE TITLE
Add documentation for __protobuf__ 

### ISSUE THREAD

**Issue by fischor** [googleapis/proto-plus-python#244]
It would be nice to have documentation on how to use the `__protobuf__ = proto.module` magic and what it actually does.
I've seen it in use here:

https://github.com/googleapis/python-automl/blob/227c08b2fa6efa5af6677efc8e35382b23915fb4/google/cloud/automl_v1/types/classification.py#L19-L26

What is the `manifest` param for?
It seems that nested messages do not need to be registered in there. Is that correct?

One problem I was facing: if you have two messages with the same name and no `__protobuf__` specified, you get an error:

```python
# a.py

class A(proto.Message):
    name = proto.Field(proto.STRING, number=1)
```

```python
# b.py

class A(proto.Message):
    name = proto.Field(proto.STRING, number=1)
```

```python
# main.py

import a
import b

_a = a.A(name="Hello, A!")
_b = b.A(name="Hello, B!")
```

```
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "b_a.proto":
  A.name: "A.name" is already defined in file "a_a.proto".
  A: "A" is already defined in file "a_a.proto".
```

So I assume with `__protobuf__ = proto.module(package="a")` and `__protobuf__ = proto.module(package="b")` you can somewhat define proto packages.

**Comment by parthea** [comment]
For https://github.com/googleapis/proto-plus-python/issues/244#issuecomment-1377612330, the issue has been fixed in https://github.com/googleapis/proto-plus-python/pull/348
