### ISSUE TITLE
huge performance problem when using append() on a repeated field

### ISSUE THREAD

**Issue by tswast** [googleapis/proto-plus-python#246]
Consider the following code sample:

```python
from google.cloud.bigquery_storage_v1beta2 import types


def dense_row_generator(proto_rows):
    """Generates rows up to a predetermined size limit."""
    available = 8 * 1024 * 1024
    rows = []
    while True:
        row_bytes = b"hello world" * 20

        if available - len(row_bytes) < 0:
            break
        available = available - len(row_bytes)

        # (1) Slow! 174.54s user 34.81s system 99% cpu 3:29.59 total
        # proto_rows.serialized_rows.append(row_bytes)

        # (2) OK: 1.68s user 0.46s system 77% cpu 2.768 total
        # proto_rows._pb.serialized_rows.append(row_bytes)

        # (3)
        rows.append(row_bytes)

    # (3) OK: 1.66s user 0.43s system 90% cpu 2.313 total
    proto_rows.serialized_rows = rows


proto_rows = types.ProtoRows()
dense_row_generator(proto_rows)
```

Since I have used the plain protobuf library before, (1) was my first intuition. This turned out to be more than 50x slower than the same code but accessing the plain protobuf directly!

Perhaps `append` shouldn't be allowed at all in `proto-plus` if it can introduce such a huge slowdown?

**Comment by software-dov** [comment]
We can't remove it without causing a breaking change; for anything that's not a hot inner loop it probably doesn't matter too much.
This is hopefully going to be improved when the protobuf team adds additional APIs for manipulating fields so we don't have to rely on hacks.

**Comment by y4n9squared** [comment]
Encountered a similar problem in a different context. Accessing the underlying `_pb` member to append directly improves performance significantly. This workaround exists in a lot of Google Python client libraries (eg. https://github.com/googleapis/python-bigtable/pull/382). 

Not sure if there is a better solution until issue is solved upstream.

**Comment by vam-google** [comment]
Lowing this down to its original priority (p3). There are lot of changes are planned for proto-plus vs native protobuf stubs in the future, and most likely this issue will be addressed indirectly as part of that work.

**Comment by parthea** [comment]
Closing as a response was provided in https://github.com/googleapis/proto-plus-python/issues/246#issuecomment-961440104 which includes a workaround for performance sensitive applications. (Googlers consider checking with the [protobuf team](https://github.com/protocolbuffers/protobuf) to determine how best to integrate directly with the protobuf API, rather than via proto-plus. Ref b/259448364)
