### ISSUE TITLE
Custom __dir__ in 1.20.0 breaks when called on 'Message' instead of subclass

### ISSUE THREAD

**Issue by saggitar** [googleapis/proto-plus-python#296]
#### Environment details

  - Programming language: Python
  - OS: Arch Linux (Kernel: Linux 5.16.5-arch1-1, Architecture: x86-64)
  - Language runtime version: tested with 3.8, 3.9, 3.10
  - Package version: 1.20.0

#### Steps to reproduce

  1. Install new proto-plus version
  2.
      ```
      >>> import proto.message
      >>> dir(proto.message.Message)
      [...]
      AttributeError: type object 'Message' has no attribute '_meta'
      ```
`_meta` is only set when new `proto.message.Message` types are created, so `__dir__` does not work on
`proto.message.Message` itself.
In this case `__dir__` should probably fall back to `object.__dir__` as it was implicitly the case in previous versions.

**Comment by software-dov** [comment]
This is my bad, fix is imminent.
