### ISSUE TITLE
Add support for DatetimeWithNanos on pb Timestamp

### ISSUE THREAD

**Issue by crwilcox** [googleapis/proto-plus-python#38]
In Google Cloud API Core, we have a class, `DatetimeWithNanoseconds`. This allows us to keep `timestamp_pb2` precision, but have pythonic interfaces.

https://github.com/googleapis/python-api-core/commit/5e121ce063bddfee174cff603668c5191876fd08

It would be great if protoplus could implement this.

**Comment by lukesneeringer** [comment]
My vote on how to do this would be to move `DatetimeWithNanoseconds` from api-core to here, and then have api-core import it and put it in `__all__` in the module where it used to be.

**Comment by crwilcox** [comment]
Funny you would comment, I was working on this now. just PR'd at https://github.com/googleapis/proto-plus-python/pull/40
