### ISSUE TITLE
`Message.to_dict()` argument `always_print_fields_with_no_presence` has no effect on Windows

### ISSUE THREAD

**Issue by silvanocerza** [googleapis/proto-plus-python#483]
#### Environment details

  - Programming language: Python 
  - OS: Windows
  - Language runtime version: CPython >=3.8
  - Package version: latest `1.24.0`

#### Steps to reproduce

1. `pip install proto-plus`
2. Create an instance of any `Message` without setting all fields
3. Call `type(message).to_dict(message, always_print_fields_with_no_presence=False)`

Fields that are not set will still be present in the returned dictionary, even if `always_print_fields_with_no_presence` should prevent that.

This happens only on Windows with `protobuf>=5.28`, pinning `protobuf` to `<5.28` prevents it.

I created a small repo to reproduce the issue. 
https://github.com/silvanocerza/protobuf-bug

See workflow runs that reproduce the issue: https://github.com/silvanocerza/protobuf-bug/actions/runs/10723276739

**Comment by esrauchg** [comment]
Thanks for bug report and clean reproduction!

Can you clarify that this does reproduce exactly only on Windows? We're investigating another very deep issue related to python on windows and I'm trying to see how likely this is to be another symptom of that.

**Comment by parthea** [comment]
Fixed via https://github.com/protocolbuffers/protobuf/pull/18160

**Comment by silvanocerza** [comment]
> Thanks for bug report and clean reproduction!
> 
> Can you clarify that this does reproduce exactly only on Windows? We're investigating another very deep issue related to python on windows and I'm trying to see how likely this is to be another symptom of that.

Yup, only Windows. 

But I see I'm late to answer. :)

Thanks for the quick release by the way, I'll be waiting for release. Is there an ETA for that?
