### ISSUE TITLE
Bad comparison operator interoperability between DateTimeWIthNanos and datetime.datetime

### ISSUE THREAD

**Issue by software-dov** [googleapis/proto-plus-python#56]
Provide an __eq__ override and one of the comparison operators (interpolate the others via https://docs.python.org/3/library/functools.html#functools.total_ordering). Special case when the other is a regular datetime.datetime.
E.g. the following is incorrect
```python
t0 = dh.DatetimeWithNanoseconds(year=2112, month=2, day=10, nanosecond=666)
t1 =  datetime(year=2112, month=2, day=10)
t1 == t0    # Currently evaluates to True 
t0 == t1    # Reflexive, also erroneously True
```

**Comment by parthea** [comment]
Closing as adding the additional validation could result in a performance impact.

As an example, if we were to use [functools.total_ordering](From https://docs.python.org/3/library/functools.html#functools.total_ordering),

```
While this decorator makes it easy to create well behaved totally ordered types, it does come at the cost of slower execution and more complex stack traces for the derived comparison methods. If performance benchmarking indicates this is a bottleneck for a given application, implementing all six rich comparison methods instead is likely to provide an easy speed boost.
```
