### ISSUE TITLE
Create proto-plus messages from classes generated by protoc

### ISSUE THREAD

**Issue by kwkbtr** [googleapis/proto-plus-python#84]
Hi, I'm interested in using this library in our project.
We currently have proto definition files (`*.proto`) and generate Python code with `protoc`.
I want to use proto-plus with the existing definitions, but could not find a way to do it.
Is there a way to create proto-plus messages from existing Python classes generated by `protoc`?
If not, is it possible that such a feature would be implemented in future?

**Comment by software-dov** [comment]
This is almost exactly what https://github.com/googleapis/gapic-generator-python/ accomplishes: it is a protoc plugin that, given protobuf descriptors, generates client libraries and proto-plus message classes. Try taking a look at that and see if it fits your needs.

So, to answer your question more directly, what you want is very possible, but it falls outside the strict scope of proto-plus and is instead accomplished by other tools.

**Comment by kwkbtr** [comment]
Thank you, I will give it a try!
